baseURL = "https://copybook-3w6.pages.dev/"
languageCode = "zh-CN"
title = "Skill Get Now"

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
canonifyURLs = false

[pagination]
  pagerSize = 30

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[taxonomies]
  tag = 'tags'
  mood = 'mood'
  category = 'categories'

[params]
  description = "技能之书 ▪ 永久免费的通识技能学习资源站，每天持续更新"
  og_image = "/images/og.jpg"
  sitename = "技能之书"

[params.author]
  name = "Lucida"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  behance = "praveenjuge"

[mediaTypes]
  [mediaTypes."text/css"]
    suffixes = ["css"]
    mediaType = "text/css"

[outputFormats]
  [outputFormats.CSS]
    mediaType = "text/css"
    isPlainText = true
    isHTML = false
    isRSS = false
    isSitemap = false
    notAlternative = true

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[resources]
  [resources.transforms]
    [resources.transforms.PostCSS]
      enabled = true
      config = "tailwind.config.js"
      source = "assets/css/main.css"
      target = "css/main.css"
      minify = true
